variables:
  BUILD_DIR: dist

workflow:
  rules:
    # Create pipeline for either the MR or the branch/tag but not both
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG =~ /^v[0-9]+/ || $CI_COMMIT_BRANCH =~ /^[0-9]+\.[0-9]+$/ || $CI_COMMIT_BRANCH =~ /^renovate\//

default:
  image: node:18.15-alpine
  interruptible: true
  before_script:
    - date
    - corepack enable
    - yarn install --immutable
  after_script:
    - date

lint:
  stage: test
  allow_failure: false
  script:
    - yarn lint

prettier:
  stage: test
  allow_failure: false
  script:
    - yarn prettier --check .

stylelint:
  stage: test
  allow_failure: false
  script:
    - yarn stylelint "**/*.scss"

unit_tests:
  stage: test
  image: particifydev/chromebrowser-nodejs:111.0.5563.64-1-nodejs-18.15.0
  allow_failure: false
  variables:
    CHROME_BIN: /usr/bin/google-chrome
  script:
    - yarn test

ngbuild:
  stage: build
  allow_failure: false
  artifacts:
    expire_in: 2 days
    paths:
      - '$BUILD_DIR'
  script:
    - sed -i "s/\$VERSION_COMMIT_HASH/$CI_COMMIT_SHA/" src/environments/environment.prod.ts
    - sed -i "s/\$VERSION_COMMIT_DATE/$CI_COMMIT_TIMESTAMP/" src/environments/environment.prod.ts
    - yarn build

docker_image:
  stage: deploy
  dependencies:
    - ngbuild
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
      variables:
        DOCKER_TAG: next
    - when: manual
      variables:
        DOCKER_TAG: dev-$CI_COMMIT_REF_SLUG
  variables:
    DOCKER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/$PROJECT
    KANIKO_CONTEXT: $CI_PROJECT_DIR
    KANIKO_DOCKERFILE: $CI_PROJECT_DIR/docker/Dockerfile
  allow_failure: true
  interruptible: false
  before_script:
    - date
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "$KANIKO_CONTEXT"
      --dockerfile "$KANIKO_DOCKERFILE"
      --destination "$DOCKER_IMAGE:$DOCKER_TAG"
      --build-arg "ARSNOVA_BUILD_DIR=`echo $BUILD_DIR`"
