variables:
  BUILD_DIR: dist

stages:
  - codestyle
  - test
  - build
  - review
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

tslint:
  stage: codestyle
  tags:
    - nodejs
  allow_failure: false
  dependencies: []
  script:
    - npm install
    - node_modules/tslint/bin/tslint -p ./tsconfig.json -c ./tslint.json --project

unit_tests:
  stage: test
  tags:
    - nodejs
  allow_failure: false
  dependencies: []
  variables:
    CHROME_BIN: /usr/bin/google-chrome
  script:
    - npm install
    - npm test

ngbuild:
  stage: build
  tags:
    - angular
  allow_failure: false
  dependencies: []
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --prod --aot
  artifacts:
    paths:
      - "$BUILD_DIR"
