variables:
  BUILD_DIR: dist
  NODE_VERSION: "12.13"

stages:
  - codestyle
  - test
  - build
  - review
  - deploy

default:
  image: node:$NODE_VERSION-buster
  before_script:
    - export PATH="`pwd`/node_modules/.bin:$PATH"
    - date
    - npm i
    - date
  after_script:
    - date

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

tslint:
  stage: codestyle
  allow_failure: false
  dependencies: []
  script:
    - node_modules/tslint/bin/tslint -p ./tsconfig.json -c ./tslint.json --project

unit_tests:
  stage: test
  image: registry.gitlab.com/arsnova/devops/docker/nodejs_chrome:201912052125
  allow_failure: false
  dependencies: []
  variables:
    CHROME_BIN: /usr/bin/google-chrome
  script:
    - npm test

ngbuild:
  stage: build
  allow_failure: false
  dependencies: []
  script:
    - ng build --prod --aot
  artifacts:
    paths:
      - "$BUILD_DIR"

docker_image:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    - master
  variables:
    KANIKO_CONTEXT: $CI_PROJECT_DIR
    KANIKO_DOCKERFILE: $CI_PROJECT_DIR/docker/Dockerfile
    KANIKO_DESTINATION: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  dependencies:
    - ngbuild
  before_script:
    - date
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "$KANIKO_CONTEXT" --dockerfile "$KANIKO_DOCKERFILE" --destination "$KANIKO_DESTINATION" --build-arg "ARSNOVA_BUILD_DIR=`echo $BUILD_DIR`"
