variables:
  BUILD_DIR: dist
  NODE_VERSION: "12.13"

stages:
  - codestyle
  - test
  - build
  - review
  - deploy

default:
  image: node:$NODE_VERSION-buster
  before_script:
    - export PATH="`pwd`/node_modules/.bin:$PATH"
    - date
    - yarn
    - date
  after_script:
    - chmod -Rf a+rwX node_modules
    - date

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

tslint:
  stage: codestyle
  allow_failure: false
  dependencies: []
  script:
    - tslint -p ./tsconfig.json -c ./tslint.json --project

unit_tests:
  stage: test
  image: registry.gitlab.com/arsnova/devops/docker/nodejs_chrome:201912052125
  allow_failure: false
  dependencies: []
  variables:
    CHROME_BIN: /usr/bin/google-chrome
  script:
    - ng test --watch=false --browsers=ChromeHeadlessCustom

ngbuild:
  stage: build
  allow_failure: false
  dependencies: []
  script:
    - ng build --prod
  artifacts:
    paths:
      - "$BUILD_DIR"

.docker_image: &docker_image
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  # Disabled for now. See https://gitlab.com/gitlab-org/gitlab/issues/34756.
  #rules:
  #  - if: '$CI_COMMIT_REF_NAME == "master"'
  #    when: on_success
  #  - if: '$CI_COMMIT_REF_NAME == "latest" || $CI_COMMIT_REF_NAME =~ /^v[0-9]+/ || $CI_COMMIT_REF_NAME =~ /^[0-9]+\.[0-9]+$/'
  #    when: never
  #  - when: manual
  variables:
    KANIKO_CONTEXT: $CI_PROJECT_DIR
    KANIKO_DOCKERFILE: $CI_PROJECT_DIR/docker/Dockerfile
    KANIKO_DESTINATION: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  dependencies:
    - ngbuild
  before_script:
    - date
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "$KANIKO_CONTEXT" --dockerfile "$KANIKO_DOCKERFILE" --destination "$KANIKO_DESTINATION" --build-arg "ARSNOVA_BUILD_DIR=`echo $BUILD_DIR`"

# Temporary workaround until GitLab bug is fixed
docker_image:
  <<: *docker_image
  only:
    - master

docker_image_dev:
  <<: *docker_image
  except:
    - master
    - latest
    - /^v[0-9]+/
    - /^[0-9]+\.[0-9]+$/
  when: manual
