variables:
  BUILD_DIR: dist
  YARN_CACHE_FOLDER: .yarn-cache

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG =~ /^v[0-9]+/ || $CI_COMMIT_BRANCH =~ /^[0-9]+\.[0-9]+$/ || $CI_COMMIT_BRANCH =~ /^renovate\/(patch-.*|-x$)/

default:
  image: node:18.12-alpine
  interruptible: true
  before_script:
    - date
  after_script:
    - date

.yarn_cache: &yarn_cache
  key: yarn-cache
  paths:
    - node_modules
    - $YARN_CACHE_FOLDER

yarn_populate_cache:
  stage: .pre
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" || $CI_MERGE_REQUEST_ID'
      when: never
    - changes:
        - package.json
        - yarn.lock
      when: always
    - when: manual
  # allow_failure: Do not block pipeline if job is created but not run.
  allow_failure: true
  cache:
    <<: *yarn_cache
    policy: pull-push
  script:
    - echo Populating cache...
    - umask 0000
    - yarn --frozen-lockfile

yarn_install:
  stage: .pre
  artifacts:
    expire_in: 2 hours
    paths:
      - node_modules
  cache:
    <<: *yarn_cache
    policy: pull
  script:
    - umask 0000
    - yarn --frozen-lockfile

lint:
  stage: test
  needs:
    - yarn_install
  allow_failure: false
  script:
    - yarn lint

unit_tests:
  stage: test
  needs:
    - yarn_install
  image: particifydev/chromebrowser-nodejs:106.0.5249.119-1-nodejs16.18.0
  allow_failure: false
  variables:
    CHROME_BIN: /usr/bin/google-chrome
  script:
    - yarn test

ngbuild:
  stage: build
  needs:
    - yarn_install
  allow_failure: false
  artifacts:
    expire_in: 2 days
    paths:
      - "$BUILD_DIR"
  script:
    - sed -i "s/\$VERSION_COMMIT_HASH/$CI_COMMIT_SHA/" src/environments/environment.prod.ts
    - sed -i "s/\$VERSION_COMMIT_DATE/$CI_COMMIT_TIMESTAMP/" src/environments/environment.prod.ts
    - yarn build

docker_image:
  stage: deploy
  dependencies:
    - ngbuild
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
      variables:
        DOCKER_TAG: next
    - when: manual
      variables:
        DOCKER_TAG: dev-$CI_COMMIT_REF_SLUG
  variables:
    DOCKER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/$PROJECT
    KANIKO_CONTEXT: $CI_PROJECT_DIR
    KANIKO_DOCKERFILE: $CI_PROJECT_DIR/docker/Dockerfile
  allow_failure: true
  interruptible: false
  before_script:
    - date
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "$KANIKO_CONTEXT"
      --dockerfile "$KANIKO_DOCKERFILE"
      --destination "$DOCKER_IMAGE:$DOCKER_TAG"
      --build-arg "ARSNOVA_BUILD_DIR=`echo $BUILD_DIR`"
