enableGlobalCache: true
nodeLinker: pnp

packageExtensions:
  '@angular-eslint/builder@*':
    dependencies:
      '@angular-devkit/architect': '*'
  '@stomp/rx-stomp@*':
    dependencies:
      uuid: '^9.0.0'
  postcss-scss@*:
    dependencies:
      postcss: '*'
